### ISSUE TITLE
Please add `apk` support (Alpine linux)

### ISSUE THREAD

**Issue by PEMessage** [jpikl/pm#1]

**Comment by jpikl** [comment]
Yeah, that's something I planed to add.

Done in the latest commit 6eef5c504c225eb98dd910c0efe48a7ceeb461d7

Could you test if it's working for you?

**Comment by PEMessage** [comment]
This works great for me! Thanks! I have only one small problem: it seems like the `BusyBox` built-in xargs doesn't support the `-o` option. Considering how widely Alpine Linux is used in Docker, maybe it would be a good idea to bypass this?

**Comment by jpikl** [comment]
It looks like [there is a workaround](https://askubuntu.com/a/1158337) for `xargs -o`. I will try to implement it.

**Comment by jpikl** [comment]
Should be fixed by bb54d6bbbf9c1a1baf253dfc8107f70863a8df81

Does this work for you?
